In [3]:
import numpy as np
from scipy import stats


In [4]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [5]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:", array1)
print("Flattened array using ravel():", array1.ravel())
print("Flattened array using flatten():", array1.flatten())

Original array: [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array using ravel(): [1 2 3 2 4 5 1 2 3]
Flattened array using flatten(): [1 2 3 2 4 5 1 2 3]


In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Are arrays equal?", np.array_equal(arr1, arr2))

Array 1: [[1 2]
 [3 4]]
Array 2: [[1 2]
 [3 4]]
Are arrays equal? True


In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements:", gfg.sum())
print("Sum of all elements row-wise:", gfg.sum(axis=1))
print("Sum of all elements column-wise:", gfg.sum(axis=0))

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [8]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Sum of diagonal elements:", np.trace(n_array))
print("Eigen values of matrix:", np.linalg.eigvals(n_array))
print("Eigen vectors of matrix:", np.linalg.eig(n_array)[1])
print("Inverse of matrix:", np.linalg.inv(n_array))
print("Determinant of matrix:", np.linalg.det(n_array))

Sum of diagonal elements: 176
Eigen values of matrix: [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [9]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Matrix multiplication:", np.dot(p, q))
print("Covariance between matrices:", np.cov(p, q))

Matrix multiplication: [[16 19]
 [26 31]]
Covariance between matrices: [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [10]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:", np.inner(x, y))
print("Outer product:", np.outer(x, y))
print("Cartesian product:", np.kron(x, y))

Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: [[ 2 10  0  3 15  0  4 20  0]
 [10 20  6 15 30  9 20 40 12]
 [ 3 15  0  2 10  0  9 45  0]
 [15 30  9 10 20  6 45 90 27]]


In [11]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Element-wise absolute value:", np.abs(array))
print("25th percentile of flattened array:", np.percentile(array.flatten(), 25))
print("50th percentile of flattened array:", np.percentile(array.flatten(), 50))
print("75th percentile of flattened array:", np.percentile(array.flatten(), 75))
print("Mean of flattened array:", np.mean(array.flatten()))
print("Median of flattened array:", np.median(array.flatten()))
print("Standard Deviation of flattened array:", np.std(array.flatten()))

Element-wise absolute value: [[1 2 3]
 [4 5 6]]
25th percentile of flattened array: -3.5
50th percentile of flattened array: -0.5
75th percentile of flattened array: 2.5
Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224


In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor values:", np.floor(a))
print("Ceiling values:", np.ceil(a))
print("Truncated values:", np.trunc(a))
print("Rounded values:", np.round(a))

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices of sorted array:", np.argsort(array))
print("4 smallest elements:", np.sort(array)[:4])
print("5 largest elements:", np.sort(array)[-5:])

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [14]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements only:", array[np.mod(array, 1) == 0])
print("Float elements only:", array[np.mod(array, 1) != 0])

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
